// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPOKdnsDZrBQcUD3iUHPyjEktmfWXbTT8',
    appId: '1:976644930625:web:63da6e655d5fcaee8e5ac0',
    messagingSenderId: '976644930625',
    projectId: 'chat-app-test-7efe9',
    authDomain: 'chat-app-test-7efe9.firebaseapp.com',
    storageBucket: 'chat-app-test-7efe9.appspot.com',
    measurementId: 'G-KVLEP6Q2XS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrJJwuexjaMTS5H8tTRoOuAiMBPr76iWc',
    appId: '1:976644930625:android:3649f4aa5e0093648e5ac0',
    messagingSenderId: '976644930625',
    projectId: 'chat-app-test-7efe9',
    storageBucket: 'chat-app-test-7efe9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVXGlzYeA4EuW17RTbbo9w6plX1wV3oqE',
    appId: '1:976644930625:ios:c3d63bcd4b79cfbc8e5ac0',
    messagingSenderId: '976644930625',
    projectId: 'chat-app-test-7efe9',
    storageBucket: 'chat-app-test-7efe9.appspot.com',
    iosClientId: '976644930625-iq5a0a0q5bvr988c9ooifs1346u4tde4.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVXGlzYeA4EuW17RTbbo9w6plX1wV3oqE',
    appId: '1:976644930625:ios:c3d63bcd4b79cfbc8e5ac0',
    messagingSenderId: '976644930625',
    projectId: 'chat-app-test-7efe9',
    storageBucket: 'chat-app-test-7efe9.appspot.com',
    iosClientId: '976644930625-iq5a0a0q5bvr988c9ooifs1346u4tde4.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPOKdnsDZrBQcUD3iUHPyjEktmfWXbTT8',
    appId: '1:976644930625:web:572efc2a4fb1be308e5ac0',
    messagingSenderId: '976644930625',
    projectId: 'chat-app-test-7efe9',
    authDomain: 'chat-app-test-7efe9.firebaseapp.com',
    storageBucket: 'chat-app-test-7efe9.appspot.com',
    measurementId: 'G-75PESD6HF7',
  );

}